### ISSUE TITLE
`RemoveListener` is missing

### ISSUE THREAD

**Issue by aytunch** [Ethiel97/bounce_tap#1]
If I am not mistaken, you add a listener but never remove it.
https://github.com/Ethiel97/bounce_tap/blob/82ccf938569ed7d5db549fd57b96ab9abfe74b41/lib/bounce_tap.dart#L53

**Comment by Ethiel97** [comment]
Hi bro! Thanks for your interest in this package. No, it's not missing. The dispose method removes all listeners under the hood.
